# Generated by Django 3.0.3 on 2022-06-07 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='recruiterdetail',
            name='created_by',
        ),
    ]
