# Generated by Django 3.0.3 on 2022-06-08 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='user',
            new_name='creted_by',
        ),
    ]
