# Generated by Django 3.0.3 on 2022-06-08 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0002_auto_20220607_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perk',
            name='job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiters.JobDetail'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiters.JobDetail'),
        ),
    ]
