# Generated by Django 3.0.3 on 2022-06-08 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0003_auto_20220608_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiters.JobDetail'),
        ),
    ]
