# Generated by Django 3.0.3 on 2022-06-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0003_auto_20220608_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='no_of_employees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
