# Generated by Django 3.0.3 on 2022-06-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0004_jobdetail_key_resposibilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetail',
            name='key_resposibilities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
