# Generated by Django 3.0.3 on 2022-06-09 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0004_auto_20220609_0546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiterdetail',
            old_name='compnay',
            new_name='company',
        ),
    ]
