# Generated by Django 3.0.3 on 2022-06-11 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruiters', '0005_auto_20220611_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryAndPerk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_salary', models.CharField(blank=True, max_length=200, null=True)),
                ('min_salary', models.CharField(blank=True, max_length=200, null=True)),
                ('max_salary', models.CharField(blank=True, max_length=200, null=True)),
                ('five_days_week', models.BooleanField(blank=True, default=False, null=True)),
                ('life_insurence', models.BooleanField(blank=True, default=False, null=True)),
                ('health_insurence', models.BooleanField(blank=True, default=False, null=True)),
                ('dress_code', models.BooleanField(blank=True, default=False, null=True)),
                ('snack_lunch', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiters.JobDetail')),
            ],
        ),
    ]
