# Generated by Django 3.0.3 on 2022-06-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.TextField(blank=True, default='Rafik Bhai Shaikh', max_length=200, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('Applicant', 'Applicant'), ('Recruiter', 'Recruiter')], default='Applicant', max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
